# Generated by Django 2.2 on 2020-04-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500, verbose_name='question')),
                ('ans1', models.CharField(max_length=100, verbose_name='ans1')),
                ('ans2', models.CharField(max_length=100, verbose_name='ans2')),
                ('ans3', models.CharField(max_length=100, verbose_name='ans3')),
                ('ans4', models.CharField(max_length=100, verbose_name='ans4')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
